config/routes.rb
GistMail::Application.routes.draw do
  resources :gists

  root :to => 'gists#index'

  devise_for :users

end

app/models/gist.rb
class Gist < ActiveRecord::Base
  validates_presence_of :count, :name, :url
end

app/models/hatena_bookmark.rb
# coding: utf-8
require 'open-uri'
require 'rexml/document'

class HatenaBookmark
  def save_today_gist
    today_gists = get_today_gist
    today_gists.each do |today_gist|
      gist = Gist.new
      gist.name = today_gist[0]
      gist.url = today_gist[1]
      gist.count = today_gist[2]
      gist.save
    end
  end

  def get_today_gist
    gist = []
    uri = URI.parse(Settings.hatena_rss_url)
    doc = uri.open {|rss| REXML::Document.new(rss)}
    doc.root.elements.each("item") do |item|
      dc_date = Time.zone.parse(item.elements["dc:date"].text)
      gist.push([
        item.elements["title"].text,
        item.attributes["about"],
        item.elements["hatena:bookmarkcount"].text
      ]) if dc_date.today?
    end
    gist
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    end
end

app/controllers/gists_controller.rb
# coding: utf-8
class GistsController < ApplicationController
  before_action :find_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.where("count > 0").order("count DESC")
    @new_gist = Gist.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @new_gist }
    end
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gist }
    end
  end

  # GET /gists/new
  # GET /gists/new.json
  def new
    @gist = Gist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gist }
    end
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)
    @gist.count = 1

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render json: @gist, status: :created, location: @gist }
      else
        format.html { redirect_to gists_url, notice: '未入力の項目があります。' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gists/1
  # PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update_attributes(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy

    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private

    def find_gist
      @gist = Gist.find(params[:id])
    end

    def gist_params
      params.require(:gist).permit(:count, :name, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gists/_entryform.html.erb
<div class="bs-docs-sidebar affix add-gist">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <%= form_for(@new_gist, :html => {:class => "navbar-form pull-left"}) do |f| %>
          <%= f.text_field :name, {:class => "span2", :placeholder => 'short name'} %>
          <%= f.text_field :url, {:class => "span4", :placeholder => 'https://gist.github.com/'} %>
          <%= f.submit 'Gistを追加', :class => 'btn btn-info' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gists/edit.html.erb
<h1>Editing gist</h1>

<%= render 'form' %>

<%= link_to 'Show', @gist %> |
<%= link_to 'Back', gists_path %>

app/views/gists/index.html.erb
<h1>本日の注目されている Gist</h1>

<ul>
  <% @gists.each do |gist| %>
    <li id="<%= gist.id %>">
      <h2 class="gist-name">
        <%= link_to gist.name, gist.url%>
      </h2>
      <ul>
        <li class="favorite-count"><%= gist.count %></li>
      </ul>
    </li>
  <% end %>
</ul>

<%= render 'entryform' %>

app/views/gists/new.html.erb
<h1>New gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path %>

app/views/gists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gist.name %>
</p>

<p>
  <b>Url:</b>
  <%= @gist.url %>
</p>

<p>
  <b>Count:</b>
  <%= @gist.count %>
</p>


<%= link_to 'Edit', edit_gist_path(@gist) %> |
<%= link_to 'Back', gists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GistMail</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<style type="text/css">
<!--
#contents {
  padding-top: 70pt;
}
-->
</style>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <h1>Gistar</h1>
      </div>
    </div>
  </div>
  <div id="contents" class="container">
    <div class="row">
      <div class="span3 bs-docs-sidebar">
        <ul class="nav nav-list bs-docs-sidenav affix">
          <div class="thumbnail">
            <% if user_signed_in? %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to 'ユーザ情報編集', edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to '新規登録', new_user_registration_path %></li>
              <li><%= link_to 'ログイン', user_session_path %></li>
              <li><%= link_to 'パスワードの再発行', new_user_password_path %></li>
            <% end %>
            <li><%= link_to 'トップ画面', root_path %></li>
          </div>
        </ul>
      </div>
      <div class="span9">
        <p><%= notice %></p>
        <p><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>